const paymentData = {
  object: "list",
  data: [
    {
      id: "price_1OGhpqCPOFLMr7u32EObB9zJ",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1701003198,
      currency: "php",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_P4rYzAoq5nhrqX",
      recurring: {
        aggregate_usage: null,
        interval: "year",
        interval_count: 1,
        trial_period_days: null,
        usage_type: "licensed",
      },
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "recurring",
      unit_amount: 2000,
      unit_amount_decimal: "2000",
    },
    {
      id: "price_1OGhppCPOFLMr7u3gxQMNGyl",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1701003197,
      currency: "php",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_P4rYzAoq5nhrqX",
      recurring: {
        aggregate_usage: null,
        interval: "month",
        interval_count: 6,
        trial_period_days: null,
        usage_type: "licensed",
      },
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "recurring",
      unit_amount: 1200,
      unit_amount_decimal: "1200",
    },
    {
      id: "price_1OGhppCPOFLMr7u3mk51y0TA",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1701003197,
      currency: "php",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_P4rYzAoq5nhrqX",
      recurring: {
        aggregate_usage: null,
        interval: "month",
        interval_count: 1,
        trial_period_days: null,
        usage_type: "licensed",
      },
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "recurring",
      unit_amount: 600,
      unit_amount_decimal: "600",
    },
    {
      id: "price_1OGhnvCPOFLMr7u3hsOqFfVB",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1701003079,
      currency: "php",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_P4rWYY1Wzrc6vC",
      recurring: {
        aggregate_usage: null,
        interval: "month",
        interval_count: 1,
        trial_period_days: null,
        usage_type: "licensed",
      },
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "recurring",
      unit_amount: 500,
      unit_amount_decimal: "500",
    },
    {
      id: "price_1OGhnvCPOFLMr7u3LVNS4MJb",
      object: "price",
      active: true,
      billing_scheme: "per_unit",
      created: 1701003079,
      currency: "php",
      custom_unit_amount: null,
      livemode: false,
      lookup_key: null,
      metadata: {},
      nickname: null,
      product: "prod_P4rWYY1Wzrc6vC",
      recurring: {
        aggregate_usage: null,
        interval: "year",
        interval_count: 1,
        trial_period_days: null,
        usage_type: "licensed",
      },
      tax_behavior: "unspecified",
      tiers_mode: null,
      transform_quantity: null,
      type: "recurring",
      unit_amount: 1000,
      unit_amount_decimal: "1000",
    },
  ],
  has_more: false,
  url: "/v1/prices",
};
